"""
validate_rl_output.py  —  Tanimoto similarity validation of RL output
======================================================================
Compares molecules generated by the RL agent against the desalted
training SMILES used for Transfer Learning.

Metrics reported per RL molecule:
  - max_tanimoto    : highest similarity to any training molecule (ECFP4)
  - mean_tanimoto   : average similarity to training set
  - is_novel        : True if max_tanimoto < 0.4 (genuinely new scaffold)
  - is_similar      : True if max_tanimoto >= 0.4 (close to training molecule)

Summary statistics:
  - % novel (max Tanimoto < 0.3)
  - % scaffold-similar (max Tanimoto 0.3–0.6)
  - % near-copies (max Tanimoto > 0.6)
  - Distribution histogram plot

Usage:
  python validate_rl_output.py
  python validate_rl_output.py --rl_csv results/focused_rl_v2_1.csv \\
         --train_smi datasets/JAK2/clean_smiles.smi
"""

import os
import glob
import argparse
import numpy as np
import pandas as pd

from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
from rdkit import RDLogger
RDLogger.DisableLog("rdApp.*")

try:
    import matplotlib.pyplot as plt
    import matplotlib
    matplotlib.use("Agg")   # headless safe
    PLOT = True
except ImportError:
    PLOT = False
    print("[WARNING] matplotlib not installed — skipping histogram plot")


# ─── Fingerprint helpers ──────────────────────────────────────────────────────
def ecfp4(smi: str):
    mol = Chem.MolFromSmiles(str(smi))
    if mol is None:
        return None
    return AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048)


def bulk_max_tanimoto(query_fp, reference_fps):
    """Return the maximum Tanimoto similarity between query_fp and all reference_fps."""
    if not reference_fps:
        return 0.0
    sims = DataStructs.BulkTanimotoSimilarity(query_fp, reference_fps)
    return float(max(sims))


def bulk_mean_tanimoto(query_fp, reference_fps):
    """Return the mean Tanimoto similarity between query_fp and all reference_fps."""
    if not reference_fps:
        return 0.0
    sims = DataStructs.BulkTanimotoSimilarity(query_fp, reference_fps)
    return float(np.mean(sims))


# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Tanimoto validation: RL output vs training data"
    )
    parser.add_argument(
        "--rl_csv", type=str, default=None,
        help="Path to RL output CSV (auto-detects latest results/focused_rl*.csv)"
    )
    parser.add_argument(
        "--train_smi", type=str, default="datasets/JAK2/clean_smiles.smi",
        help="Path to training SMILES file (default: datasets/JAK2/clean_smiles.smi)"
    )
    parser.add_argument(
        "--out_dir", type=str, default="results",
        help="Output directory for validation CSV + plot (default: results/)"
    )
    parser.add_argument(
        "--novel_thresh", type=float, default=0.3,
        help="Max Tanimoto below which a molecule is 'novel' (default: 0.3)"
    )
    parser.add_argument(
        "--similar_thresh", type=float, default=0.6,
        help="Max Tanimoto above which a molecule is a 'near-copy' (default: 0.6)"
    )
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    # ── Find RL output CSV ───────────────────────────────────────────────────
    if args.rl_csv:
        rl_csv = args.rl_csv
    else:
        csvs = sorted(glob.glob(os.path.join("results", "focused_rl*.csv")))
        if not csvs:
            print("[ERROR] No RL results CSV found in results/. "
                  "Run the pipeline first or specify --rl_csv")
            return
        rl_csv = csvs[-1]
    print(f"\n[*] RL output CSV:   {rl_csv}")
    print(f"[*] Training SMILES: {args.train_smi}")

    # ── Load RL molecules ────────────────────────────────────────────────────
    rl_df = pd.read_csv(rl_csv)
    smiles_col = "SMILES" if "SMILES" in rl_df.columns else rl_df.columns[0]

    # Keep only accepted molecules (Score > 0) and deduplicate
    if "Score" in rl_df.columns:
        rl_df = rl_df[rl_df["Score"] > 0]
    rl_df = rl_df.drop_duplicates(subset=[smiles_col]).reset_index(drop=True)
    print(f"[*] Unique accepted RL molecules: {len(rl_df):,}")

    # ── Load training SMILES ─────────────────────────────────────────────────
    if not os.path.exists(args.train_smi):
        print(f"[ERROR] Training SMILES file not found: {args.train_smi}")
        return

    with open(args.train_smi) as f:
        train_smiles = [line.strip() for line in f if line.strip()]
    print(f"[*] Training set size: {len(train_smiles):,}")

    # ── Compute training fingerprints ────────────────────────────────────────
    print("[*] Computing training set ECFP4 fingerprints...")
    train_fps = []
    n_invalid_train = 0
    for smi in train_smiles:
        fp = ecfp4(smi)
        if fp is not None:
            train_fps.append(fp)
        else:
            n_invalid_train += 1
    print(f"    Valid training FPs: {len(train_fps):,} "
          f"(skipped {n_invalid_train} invalid SMILES)")

    # ── Compute per-molecule Tanimoto ────────────────────────────────────────
    print("[*] Computing Tanimoto similarities (this may take a moment)...")
    max_tanimotos  = []
    mean_tanimotos = []
    valid_rl       = []

    for smi in rl_df[smiles_col]:
        fp = ecfp4(smi)
        if fp is None:
            max_tanimotos.append(np.nan)
            mean_tanimotos.append(np.nan)
            valid_rl.append(False)
            continue
        max_tanimotos.append(bulk_max_tanimoto(fp, train_fps))
        mean_tanimotos.append(bulk_mean_tanimoto(fp, train_fps))
        valid_rl.append(True)

    rl_df["max_tanimoto"]  = max_tanimotos
    rl_df["mean_tanimoto"] = mean_tanimotos
    rl_df["valid_smiles"]  = valid_rl

    # ── Classify ─────────────────────────────────────────────────────────────
    valid_mask = rl_df["valid_smiles"]
    max_tan    = rl_df.loc[valid_mask, "max_tanimoto"]

    n_valid   = valid_mask.sum()
    n_novel   = (max_tan < args.novel_thresh).sum()
    n_scaffold = ((max_tan >= args.novel_thresh) & (max_tan < args.similar_thresh)).sum()
    n_copy    = (max_tan >= args.similar_thresh).sum()

    print(f"\n{'='*55}")
    print(f"  Tanimoto Validation Summary")
    print(f"{'='*55}")
    print(f"  Total RL molecules (accepted):  {len(rl_df):,}")
    print(f"  Valid SMILES (parseable):        {n_valid:,}")
    print(f"")
    print(f"  Similarity thresholds:")
    print(f"    Novel         (max Tan < {args.novel_thresh}):    "
          f"{n_novel:,}  ({n_novel/n_valid*100:.1f}%)")
    print(f"    Scaffold-sim  ({args.novel_thresh} ≤ max Tan < {args.similar_thresh}): "
          f"{n_scaffold:,}  ({n_scaffold/n_valid*100:.1f}%)")
    print(f"    Near-copy     (max Tan ≥ {args.similar_thresh}):   "
          f"{n_copy:,}  ({n_copy/n_valid*100:.1f}%)")
    print(f"")
    print(f"  Max Tanimoto stats:")
    print(f"    Mean:   {max_tan.mean():.3f}")
    print(f"    Median: {max_tan.median():.3f}")
    print(f"    Min:    {max_tan.min():.3f}")
    print(f"    Max:    {max_tan.max():.3f}")

    # Show pIC50 by novelty band if column available
    raw_col = None
    if "JAK2pIC50_raw" in rl_df.columns:
        raw_col = "JAK2pIC50_raw"
    elif "JAK2pIC50 (raw)" in rl_df.columns:
        raw_col = "JAK2pIC50 (raw)"

    if raw_col:
        print(f"\n  Mean predicted pIC50 by novelty band (column: {raw_col}):")
        novel_mask   = valid_mask & (rl_df["max_tanimoto"] < args.novel_thresh)
        scaf_mask    = valid_mask & (rl_df["max_tanimoto"] >= args.novel_thresh) & \
                       (rl_df["max_tanimoto"] < args.similar_thresh)
        copy_mask    = valid_mask & (rl_df["max_tanimoto"] >= args.similar_thresh)
        for label, mask in [("Novel", novel_mask), ("Scaffold-sim", scaf_mask),
                            ("Near-copy", copy_mask)]:
            if mask.any():
                mean_pic50 = rl_df.loc[mask, raw_col].mean()
                print(f"    {label:<14}: {mean_pic50:.3f}")

    print(f"{'='*55}")

    # ── Save results CSV ──────────────────────────────────────────────────────
    out_csv = os.path.join(args.out_dir, "rl_validation.csv")
    rl_df.to_csv(out_csv, index=False)
    print(f"\n✅ Detailed results saved → {out_csv}")

    # ── Plot histogram ────────────────────────────────────────────────────────
    if PLOT and n_valid > 0:
        fig, ax = plt.subplots(figsize=(10, 5))
        ax.hist(max_tan, bins=40, color="#4C72B0", edgecolor="white", alpha=0.85)
        ax.axvline(args.novel_thresh,   color="#DD4444", linestyle="--",
                   linewidth=1.8, label=f"Novel threshold ({args.novel_thresh})")
        ax.axvline(args.similar_thresh, color="#44AA44", linestyle="--",
                   linewidth=1.8, label=f"Near-copy threshold ({args.similar_thresh})")
        ax.set_xlabel("Max Tanimoto Similarity to Training Set (ECFP4)", fontsize=12)
        ax.set_ylabel("Count of RL Molecules", fontsize=12)
        ax.set_title("RL Output Novelty vs Training Data\n"
                     f"({n_novel}/{n_valid} novel  |  "
                     f"{n_copy}/{n_valid} near-copies)", fontsize=13)
        ax.legend(fontsize=11)
        ax.grid(axis="y", alpha=0.3)
        plot_path = os.path.join(args.out_dir, "rl_tanimoto_histogram.png")
        plt.tight_layout()
        plt.savefig(plot_path, dpi=150)
        plt.close()
        print(f"✅ Histogram plot saved → {plot_path}")


if __name__ == "__main__":
    main()
