
run_type = "sampling"
device = "cpu"
tb_logdir = "tb_pd1_pdl1_eval_e60"
json_out_config = "json_pd1_pdl1_eval_e60.json"
[parameters]
model_file = "/Users/vishnukasturi/Intern/reinvent-local/models/pd1_pdl1_TL.model.60.chkpt"
output_file = "/Users/vishnukasturi/Intern/reinvent-local/results/pd1_pdl1_tl_sample_e60.csv"
num_smiles = 500
unique_molecules = true
randomize_smiles = true
