run_type = "sampling"
device = "cpu"
json_out_config = "json_jak2_sampling_rl_run6.json"

[parameters]
model_file = "/Users/vishnukasturi/Intern/reinvent-local/models/jak2_rl_run6.chkpt"
num_smiles = 5000
output_file = "/Users/vishnukasturi/Intern/reinvent-local/results/jak2_rl_candidates_run6.csv"

unique_molecules = true
sample_strategy = "multinomial"
temperature = 1.0
