run_type = "sampling"
device = "cpu"
json_out_config = "json_jak2_sampling_rl_run4.json"

[parameters]
model_file = "../models/jak2_rl_final_run4.model"
num_smiles = 5000
output_file = "../results/jak2_rl_candidates_run4.csv"

unique_molecules = true
sample_strategy = "multinomial"
temperature = 1.0
