run_type = "transfer_learning"
device   = "cpu"
tb_logdir       = "../tb_pd1_pdl1_TL"
json_out_config = "json_pd1_pdl1_TL.json"

[parameters]
num_epochs          = 100
batch_size          = 128
save_every_n_epochs = 10

# Paths relative to REINVENT4/ directory
input_model_file          = "priors/reinvent.prior"
smiles_file               = "../data/pd1_pdl1_TL_train.smi"
validation_smiles_file    = "../data/pd1_pdl1_TL_val.smi"
output_model_file         = "../models/pd1_pdl1_TL.model"

standardize_smiles = true
randomize_smiles   = true
